name: test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Running go tests
        env:
          GO111MODULE: on
        run: make test